create database RetailPulseDB;

use RetailPulseDB;
-- Customers
CREATE TABLE Customers (
CustomerID INT PRIMARY KEY IDENTITY(1,1),
CustomerName VARCHAR(100),
City VARCHAR(50),
SignupDate DATE
);

--Products
CREATE TABLE Products (
ProductID INT PRIMARY KEY IDENTITY(1,1),
ProductName VARCHAR(100),
Category VARCHAR(50),
Price DECIMAL(10,2)
);

-- orders
CREATE TABLE Orders (
OrderID INT PRIMARY KEY IDENTITY(1,1),
CustomerID INT,
OrderDate DATE,
FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

-- orderDetails
CREATE TABLE OrderDetails (
OrderDetailID INT PRIMARY KEY IDENTITY(1,1),
OrderID INT,
ProductID INT,
Quantity INT,
FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);
--Customers (realistic signup spread)
INSERT INTO Customers (CustomerName, City, SignupDate) VALUES
('Ravi Kumar', 'Hyderabad', '2024-01-10'),
('Sneha Reddy', 'Bangalore', '2024-01-18'),
('Aman Verma', 'Delhi', '2024-02-05'),
('Megha Singh', 'Mumbai', '2024-02-20'),
('Karan Gupta', 'Pune', '2024-03-01'),
('Divya Sharma', 'Kolkata', '2024-03-15'),
('Priya Nair', 'Chennai', '2024-04-02'),
('Vikram Das', 'Lucknow', '2024-04-20');

--Products (categories that matter)
INSERT INTO Products (ProductName, Category, Price) VALUES
('Wireless Mouse', 'Electronics', 799.00),
('Mechanical Keyboard', 'Electronics', 3499.00),
('USB-C Charger', 'Electronics', 1299.00),
('Office Chair', 'Furniture', 7499.00),
('Study Table', 'Furniture', 11999.00),
('Notebook Pack', 'Stationery', 299.00),
('Pen Set', 'Stationery', 199.00),
('Water Bottle', 'Accessories', 499.00),
('Laptop Backpack', 'Accessories', 2499.00);

--Orders (multiple orders per customer — IMPORTANT)
INSERT INTO Orders (CustomerID, OrderDate) VALUES
(1, '2024-03-10'),
(1, '2024-04-05'),
(2, '2024-03-12'),
(2, '2024-05-01'),
(3, '2024-04-15'),
(4, '2024-04-20'),
(5, '2024-05-02'),
(6, '2024-05-18'),
(7, '2024-06-01'),
(8, '2024-06-10');

INSERT INTO OrderDetails (OrderID, ProductID, Quantity) VALUES
-- Order 1
(1, 1, 2),   -- Wireless Mouse
(1, 6, 3),   -- Notebook Pack

-- Order 2
(2, 2, 1),   -- Mechanical Keyboard
(2, 8, 1),   -- Water Bottle

-- Order 3
(3, 3, 2),   -- USB-C Charger
(3, 7, 2),   -- Pen Set

-- Order 4
(4, 9, 1),   -- Laptop Backpack

-- Order 5
(5, 4, 1),   -- Office Chair

-- Order 6
(6, 5, 1),   -- Study Table
(6, 6, 5),   -- Notebook Pack

-- Order 7
(7, 1, 1),
(7, 8, 2),

-- Order 8
(8, 2, 1),

-- Order 9
(9, 9, 1),

-- Order 10
(10, 3, 1),
(10, 7, 3);

SELECT 
    o.OrderID,
    c.CustomerName,
    SUM(od.Quantity * p.Price) AS OrderTotal
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY o.OrderID, c.CustomerName
ORDER BY OrderTotal DESC;


--Find total revenue generated by each customer
SELECT
c.CustomerName,
SUM(od.Quantity * p.Price) AS TotalRevenue
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY c.CustomerName
ORDER BY TotalRevenue DESC;


--Identify the top-selling product in each category

WITH ProductSales AS (
SELECT
p.Category,
p.ProductName,
SUM(od.Quantity) AS UnitsSold,
RANK() OVER (
PARTITION BY p.Category
ORDER BY SUM(od.Quantity) DESC
) AS rnk
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.Category, p.ProductName
)
SELECT Category, ProductName, UnitsSold
FROM ProductSales
WHERE rnk = 1;

--Find customers who placed more than 3 orders
SELECT
c.CustomerName,
COUNT(o.OrderID) AS OrderCount
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerName
HAVING COUNT(o.OrderID) > 3;

--Calculate average order value per customer

SELECT
c.CustomerName,
AVG(OrderTotal) AS AvgOrderValue
FROM (
SELECT
o.OrderID,
o.CustomerID,
SUM(od.Quantity * p.Price) AS OrderTotal
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY o.OrderID, o.CustomerID
) t
JOIN Customers c ON t.CustomerID = c.CustomerID
GROUP BY c.CustomerName;

--Identify inactive customers (no orders in last 90 days)
SELECT c.CustomerID, c.CustomerName
FROM Customers c
LEFT JOIN Orders o
ON c.CustomerID = o.CustomerID
AND o.OrderDate >= DATEADD(DAY, -90, GETDATE())
WHERE o.OrderID IS NULL;

--Monthly revenue trend

SELECT
FORMAT(o.OrderDate, 'yyyy-MM') AS Month,
SUM(od.Quantity * p.Price) AS MonthlyRevenue
FROM Orders o
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY FORMAT(o.OrderDate, 'yyyy-MM')
ORDER BY Month;

-- Rank customers by lifetime value

SELECT
CustomerName,
TotalRevenue,
RANK() OVER (ORDER BY TotalRevenue DESC) AS RevenueRank
FROM (
SELECT
c.CustomerName,
SUM(od.Quantity * p.Price) AS TotalRevenue
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
JOIN OrderDetails od ON o.OrderID = od.OrderID
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY c.CustomerName
) t;